
const dados = [


  {
    "anos-iniciais": [
      {
        "ano": "1º",
        "disciplinas": [
          "Arte",
          "Ciências",
          "Educação Física",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português"
        ],
        "conteudos": {
          "Arte": [
            //
            "Interpretação e Análise",
            "Jogos teatrais",
            "Matrizes artísticas brasileiras",
            "Movimento e exploração do gesto",
            "Museus",
            "Obras de arte visuais",
            "Outros",
            "Percussão corporal",
            "Pré-História",
            "Produção do som",
            "Profissionais do teatro",
            "Relações processuais entre diferentes linguagens artísticas",
            "Técnicas utilizadas nas artes visuais",
            "Tipos de danças",
            "Tipos teatrais"
          ],
          "Ciências": [
            "Ambientes naturais",
            "Corpo humano",
            "Materiais",
            "Nutrição",
            "Recursos naturais",
            "Som",
            "Vida"
          ],
          "Educação Física": [
            "Esporte e inclusão social"
          ],
          "Geografia": [
            "Elementos da Paisagem e Suas Interações",
            "Introdução à Geografia",
            "Mundo",
            "O sujeito e a sociedade",
            "Pensamento espacial"
          ],
          "História": [
            "A comunidade e seus registros",
            "Cidadania e Direitos",
            "Cultura",
            "Família e Comunidade",
            "Os dias e as semanas"
          ],
          "Inglês": [
            "Adjetivos",
            "Pronomes",
            "Substantivos",
            "Verbos",
            "Vocabulary"
          ],
          "Matemática": [
            "Comprimento",
            "Geometria Espacial",
            "Geometria Plana",
            "Identificação dos números",
            "Localização",
            "Operações com números",
            "Sequências",
            "Sistema monetário",
            "Tempo"
          ],
          "Português": [
            "As letras K, W e Y",
            "Brincadeiras com sílabas",
            "Competência leitora",
            "Definição, reconhecimento e interpretação",
            "Emprego de L e LH",
            "Maiúscula e minúscula",
            "Numerais",
            "Ordem alfabética",
            "Representação gráfica",
            "Semântica",
            "Vogais e consoantes"
          ]
        }
      },
      {
        "ano": "2º",
        "disciplinas": [
          "Arte",
          "Ciências",
          "Educação Física",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português"
        ],
        "conteudos": {
          "Arte": [
            "Brincadeiras e brinquedos",
            "Elementos constitutivos das Artes visuais",
            "Figuras"
          ],
          "Ciências": [
            "Animais",
            "Células e estruturas celulares",
            "Corpo humano",
            "Ecologia",
            "Luz",
            "Materiais",
            "Nutrição",
            "Planeta Terra",
            "Recursos naturais",
            "Saneamento básico",
            "Sistema solar",
            "Sistema Terra-Lua",
            "Teias alimentares",
            "Universo",
            "Vida"
          ],
          "Educação Física": [
            "Conceituação de jogos, brincadeiras e esporte",
            "Jogos do Brasil e do Mundo"
          ],
          "Geografia": [
            "Água",
            "Brasil",
            "Cidade",
            "Elementos da Paisagem e Suas Interações",
            "Gestão de Recursos Naturais",
            "Introdução à Geografia",
            "Mundo",
            "Os lugares de viver e conviver",
            "Pensamento espacial"
          ],
          "História": [
            "A comunidade e seus registros",
            "Cidadania e Direitos",
            "Culturas indígenas americanas",
            "Diferenças Sociais",
            "Diversidade e Inclusão",
            "Espaço privado",
            "Família e Comunidade",
            "História e memória",
            "História Local",
            "História Pública",
            "Meio Ambiente e Sustentabilidade",
            "Os dias e as semanas",
            "Passagem do tempo",
            "Trabalho",
            "Tradições Culturais"
          ],
          "Inglês": [
            "Adjetivos",
            "Adjetivos Possessivos",
            "Advérbios de lugar",
            "Formas de perguntar",
            "Pronomes",
            "Substantivos",
            "Verbos",
            "Vocabulary"
          ],
          "Matemática": [
            "Comprimento",
            "Estatística",
            "Geometria Espacial",
            "Geometria Plana",
            "Identificação dos números",
            "Localização",
            "Massa",
            "Operações com números",
            "Sistema monetário",
            "Tempo",
            "Volume"
          ],
          "Português": [
            "Atividades de rima e aliteração",
            "Competência leitora",
            "Definição, reconhecimento e interpretação",
            "Emprego de C e Ç",
            "Emprego de C, CH, Ç, S, SS e Z",
            "Emprego de L e LH",
            "Emprego e J e G",
            "Maiúscula e minúscula",
            "Ordem alfabética",
            "Ortografia",
            "Pontuação",
            "Semântica (1)",
            "Semântica (2)",
            "Sílabas",
            "Substantivos"
          ]
        }
      },
      {
        "ano": "3º",
        "disciplinas": [
          "Arte",
          "Ciências",
          "Educação Física",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português"
        ],
        "conteudos": {
          "Arte": [
            "Arte africana",
            "Arte indígena",
            "Culturas regionais",
            "Dança"
          ],
          "Ciências": [
            "Aquecimento global",
            "Atmosfera",
            "Ciclo da água",
            "Corpo humano",
            "Ecologia",
            "Energia",
            "Matéria e suas transformações",
            "Planeta Terra",
            "Recursos renováveis e não renováveis",
            "Seres vivos",
            "Sistema solar",
            "Teias alimentares",
            "Vida"
          ],
          "Educação Física": [
            "Jogos cooperativos",
            "Ritmo e movimento"
          ],
          "Geografia": [
            "Brasil e suas regiões",
            "Clima",
            "Elementos da Paisagem e Suas Interações",
            "Mapas",
            "Recursos naturais",
            "Sociedade e meio ambiente",
            "Vegetação"
          ],
          "História": [
            "Culturas e tradições africanas",
            "Cultura popular",
            "Democracia",
            "Família e Comunidade",
            "História Local",
            "Povos indígenas do Brasil",
            "Trabalho e economia"
          ],
          "Inglês": [
            "Advérbios",
            "Conjunções",
            "Pronomes pessoais",
            "Vocabulário avançado"
          ],
          "Matemática": [
            "Divisão",
            "Frações",
            "Geometria Plana",
            "Identificação de padrões",
            "Multiplicação",
            "Números decimais",
            "Operações matemáticas"
          ],
          "Português": [
            "Análise de texto",
            "Concordância verbal",
            "Construção de frases",
            "Emprego de pronomes",
            "Ortografia avançada",
            "Pontuação",
            "Semântica"
          ]
        }
      },
      {
        "ano": "4º",
        "disciplinas": [
          "Arte",
          "Ciências",
          "Educação Física",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português"
        ],
        "conteudos": {
          "Arte": [
            "Arte moderna brasileira",
            "Escultura",
            "Música brasileira",
            "Técnicas de pintura"
          ],
          "Ciências": [
            "Cadeia alimentar",
            "Clima e mudanças climáticas",
            "Corpo humano",
            "Energias renováveis",
            "Física básica",
            "Matéria e energia",
            "Órgãos dos sentidos",
            "Sistema solar",
            "Vida"
          ],
          "Educação Física": [
            "Atividades rítmicas",
            "Esportes e regras"
          ],
          "Geografia": [
            "Aspectos econômicos do Brasil",
            "Formação do território brasileiro",
            "Meio ambiente e sustentabilidade",
            "Paisagem e cultura",
            "População brasileira"
          ],
          "História": [
            "Brasil Colônia",
            "Cultura afro-brasileira",
            "Escravidão no Brasil",
            "História indígena",
            "Trabalho e economia"
          ],
          "Inglês": [
            "Construção de sentenças",
            "Perguntas e respostas",
            "Vocabulário avançado"
          ],
          "Matemática": [
            "Cálculo mental",
            "Divisão de números naturais",
            "Frações equivalentes",
            "Geometria Espacial",
            "Problemas matemáticos",
            "Unidades de medida"
          ],
          "Português": [
            "Conjugação verbal",
            "Interpretação textual",
            "Ortografia avançada",
            "Regras gramaticais",
            "Redação"
          ]
        }
      },
      {
        "ano": "5º",
        "disciplinas": [
          "Arte",
          "Ciências",
          "Educação Física",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português"
        ],
        "conteudos": {
          "Arte": [
            "Arte contemporânea",
            "Cultura e identidade",
            "Movimentos artísticos",
            "Teatro brasileiro"
          ],
          "Ciências": [
            "Aquecimento global",
            "Astronomia",
            "Cadeia alimentar",
            "Células",
            "Efeitos da poluição",
            "Física básica",
            "Fósseis",
            "Matéria e energia",
            "Órgãos do corpo humano",
            "Sistema digestório",
            "Vida"
          ],
          "Educação Física": [
            "Coordenação motora",
            "Jogos competitivos"
          ],
          "Geografia": [
            "Aspectos culturais do Brasil",
            "Globalização",
            "Mapa político do Brasil",
            "Paisagens naturais e modificadas",
            "População e urbanização"
          ],
          "História": [
            "Brasil Império",
            "Cidadania e direitos humanos",
            "História africana e afro-brasileira",
            "Industrialização no Brasil",
            "Período colonial"
          ],
          "Inglês": [
            "Conjunções",
            "Pronomes reflexivos",
            "Tempos verbais",
            "Vocabulário extenso"
          ],
          "Matemática": [
            "Áreas e perímetros",
            "Frações e decimais",
            "Geometria Espacial",
            "Problemas avançados",
            "Proporções e razões"
          ],
          "Português": [
            "Análise de texto complexa",
            "Coerência textual",
            "Figuras de linguagem",
            "Ortografia oficial",
            "Redação criativa"
          ]
        }
      }
    ]
  },
  {
    "anos-finais": [
      {
        "ano": "6º",
        "disciplinas": [
          "Arte",
          "Ciências",
          "Educação Física",
          "Espanhol",
          "Filosofia",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português"
        ],
        "conteudos": {
          "Arte": [
            "Apreciação Pessoal",
            "Arte Indiana",
            "Cultura artística regional",
            "Culturas que aparecem em tempos variados (estudar segundo os contextos)",
            "Dança e significado",
            "Definições de Arte",
            "Elementos constitutivos da música",
            "Elementos constitutivos das artes visuais",
            "Elementos do espetáculo teatral",
            "Espaços de exposição de obras de arte",
            "Estilos Artísticos",
            "Gêneros teatrais",
            "História da dança",
            "História da música",
            "História do teatro",
            "Idade Antiga",
            "Interpretação e Análise",
            "Materiais utilizados nas artes visuais",
            "Matrizes artísticas brasileiras",
            "Obras de arte visuais",
            "Pré-História",
            "Profissionais do teatro"
          ],
          "Ciências": [
            "Ácidos",
            "Algas",
            "Ambientes naturais",
            "Angiospermas",
            "Aplicações das Propriedades das Ondas",
            "Aplicações do Som",
            "Audição",
            "Bases",
            "Biologia celular",
            "Biomas",
            "Biomas brasileiros",
            "Bioquímica",
            "Biotecnologia",
            "Cadeias e teias alimentares",
            "Calorimetria",
            "Características morfológicas e fisiológicas (1)",
            "Características morfológicas e fisiológicas (2)",
            "Ciclo celular",
            "Ciclos biogeoquímicos",
            "Circuitos Elétricos",
            "Classificação",
            "Climatologia",
            "Comportamento do Som",
            "Consumo de energia elétrica",
            "Controle ambiental e saneamento básico",
            "Controle de Poluição",
            "Corrente Elétrica",
            "Cosmologia Observacional",
            "Densidade e Massa Específica",
            "Dependência química (uso de drogas)",
            "Desastres Ambientais",
            "Desenvolvimento Sustentável",
            "Desequilíbrio em ecossistemas",
            "DNA",
            "Doenças causadas por bactérias (bacterioses)",
            "Doenças causadas por fungos (micoses)",
            "Doenças causadas por protozoários (protozooses)",
            "Doenças causadas por vírus (viroses)",
            "Ecossistemas aquáticos",
            "Elementos químicos",
            "Energia nuclear",
            "Especiação",
            "Estrutura Atômica",
            "Estrutura e Formação da Terra",
            "Estrutura e função",
            "Evolução",
            "Fatores que afetam a velocidade de reação",
            "Fenômenos Sonoros",
            "Fermentação",
            "Filo Annelida",
            "Filo Arthropoda",
            "Filo Chordata (Cordados)",
            "Filo Mollusca (Moluscos)",
            "Filo Nematoda (Nematódeos)",
            "Filo Platyhelmintes (Platelmintos)",
            "Filo Porifera (Poríferos)",
            "Fisiologia celular",
            "Fluxo de energia",
            "Forças e movimento",
            "Fundo de Micro-ondas Cósmico",
            "Geologia e solo",
            "Gimnospermas",
            "Gravitação Universal",
            "Hidrosfera",
            "Influência na Terra",
            "Instrumentos e Técnicas Observacionais",
            "Introdução à histologia",
            "Introdução ao estudo da ecologia",
            "Introdução aos Efeitos Ambientais de Substâncias Químicas",
            "IST (Infecções Sexualmente Transmissíveis)",
            "Leis de Newton",
            "Leis Ponderais",
            "Litosfera",
            "Manejo dos recursos naturais",
            "Máquinas simples",
            "Movimento dos corpos celestes",
            "Movimentos",
            "Noções de filogenética",
            "Óptica da visão",
            "Peixes",
            "pH e pOH",
            "Poluentes Atmosféricos",
            "Poluição da Água",
            "Poluição do Solo",
            "Ponto de Fusão e Ponto de Ebulição",
            "Populações humanas",
            "Processo fotossintético",
            "Processos de separação de misturas",
            "Propriedades de Estados da Matéria",
            "Propriedades dos Elementos",
            "Propriedades Físicas do Som",
            "Pteridófitas",
            "Qualidades Perceptivas do Som",
            "Reino Metazoa (zoologia)",
            "Reino Monera",
            "Reino Plantae (biologia vegetal)",
            "Reino Protoctista",
            "Relações ecológicas",
            "Relações Interespecíficas",
            "Relevo terrestre",
            "Saúde",
            "Saúde Pública",
            "Separação de Misturas",
            "Sistema cardiovascular",
            "Sistema digestório",
            "Sistema endócrino",
            "Sistema genital feminino",
            "Sistema imunitário e linfático",
            "Sistema locomotor",
            "Sistema nervoso central",
            "Sistema nervoso e autônomo",
            "Sistema nervoso periférico",
            "Sistema respiratório",
            "Sistema sensorial",
            "Sistema Solar",
            "Sistema urinário",
            "Sucessão ecológica e comunidades clímax",
            "Tecido hematopoiético e sanguíneo",
            "Tecido nervoso",
            "Tecido ósseo, sistema esquelético e tecido cartilaginoso",
            "Tecidos (Epitelial, Muscular, Nervoso, etc.)",
            "Tecnologias Ambientais",
            "Teorias evolutivas",
            "Termodinâmica",
            "Termometria",
            "Tipos de Galáxias",
            "Tipos de Reações Químicas",
            "Trabalho, energia e os teoremas"
          ],
          "Educação Física": [
            "Conceituação de expressão corporal, ginástica, danças, lutas e brigas",
            "Conceituação de jogos, brincadeiras e esporte",
            "Conceituação de saúde e atividade física",
            "Dança e lazer",
            "Esporte e espetáculo",
            "Esporte e inclusão social",
            "Esportes de marca",
            "Jogos e Simulações",
            "Modalidades coletivas",
            "Modalidades individuais",
            "Origem e História"
          ],
          "Espanhol": [
            "Adjetivos",
            "Apreensão de sentido",
            "Artículos",
            "Definição, reconhecimento e interpretação",
            "Habilidades de leitura",
            "Léxico",
            "Numerales",
            "Pronombres",
            "Variedades linguísticas",
            "Verbos"
          ],
          "Filosofia": [
            "Empirismo",
            "Epistemologia",
            "Estética",
            "Filosofia antiga",
            "Filosofia Contemporânea",
            "Filosofia da Ciência",
            "Filosofia medieval",
            "Filosofia Moderna",
            "Globalização",
            "Mito e religião",
            "Moral e ética",
            "O pensamento filosófico",
            "Vida social"
          ],
          "Geografia": [
            "Água",
            "Astronomia",
            "Biogeografia",
            "Campo",
            "Campo e cidade",
            "Climatologia (1)",
            "Climatologia (2)",
            "Desenvolvimento Econômico",
            "Desenvolvimento Sustentável",
            "Divisão territorial do mundo - Continentes",
            "Fontes de energia",
            "Geografia da Saúde",
            "Geografia Urbana",
            "Geologia",
            "Geomorfologia",
            "Geopolítica e relações internacionais",
            "Geoprocessamento",
            "Gestão de Recursos Naturais",
            "Globalização e desenvolvimento técnico-científico",
            "Hidrografia",
            "História da Cartografia",
            "Introdução à Geografia",
            "Mapas Digitais e Tecnologias de Navegação",
            "Migrações",
            "Movimentos do planeta Terra",
            "Pedologia",
            "Pensamento espacial",
            "População e Demografia",
            "Princípios da Cartografia",
            "Regiões e regionalização: conceitos e critérios",
            "Regionalização do Brasil",
            "Sistemas de Referência Geográfica",
            "Tipos de Mapas",
            "Vegetação",
            "Visualização de Dados Espaciais"
          ],
          "História": [
            "A origem do ser humano",
            "A pré-história americana",
            "América Colonial",
            "América Contemporânea",
            "América Espanhola no período colonial",
            "América Pré-Colombiana",
            "Baixa Idade Média",
            "Brasil Colonial",
            "Brasil Império",
            "Civilizações da Antiguidade Clássica",
            "Civilizações da Antiguidade Oriental",
            "Colonização europeia",
            "Crises e transformações",
            "Cristianismo e Igreja Medieval",
            "Cultura e Arte Medieval",
            "Culturas indígenas americanas",
            "Desenvolvimento tecnológico e científico",
            "Era Vargas",
            "Estudo da História (1)",
            "Estudo da História (2)",
            "Evolução do Pensamento Historiográfico",
            "Evolução dos Sistemas Internacionais e Instituições Globais",
            "Expansão Islâmica e Mundo Islâmico",
            "Feudalismo e Sociedade Feudal",
            "Formação dos Estados Nacionais",
            "Guerra Fria e suas consequências",
            "História Pública",
            "Idade dos Metais",
            "Império Bizantino",
            "Independências da África",
            "Independências da América",
            "Independências da Ásia",
            "Neolítico",
            "Paleolítico",
            "Períodos da Idade Média",
            "Populismo na América Latina",
            "Povoamento da América",
            "Povos germânicos",
            "Pré-história do Brasil: primeiros habitantes",
            "Questões Contemporâneas",
            "Reinos e Impérios Africanos",
            "Reinos no medievo",
            "Tráfico Transatlântico de Escravizados",
            "Unificações e movimentos nacionalistas"
          ],
          "Inglês": [
            "Adjetivos",
            "Advérbios",
            "Apreensão de sentido",
            "Artigos",
            "Atualidades",
            "Componentes essenciais da comunicação",
            "Conditional Sentences",
            "Conjunções",
            "Construções frasais",
            "Definição, reconhecimento e interpretação",
            "Formas de perguntar",
            "Habilidades de leitura",
            "Prepositions",
            "Pronomes",
            "Question Words",
            "Semântica",
            "Substantivos",
            "Verb forms",
            "Verbo to be",
            "Verbos",
            "Verbos modais",
            "Vocabulary"
          ],
          "Matemática": [
            "Expressões Algébricas",
            "Funções",
            "Geometria Analítica",
            "Geometria espacial",
            "Geometria Plana",
            "Localização",
            "Lógica (1)",
            "Lógica (2)",
            "Matemática Financeira",
            "Medidas de massa",
            "Medidas de temperatura",
            "Medidas de tempo",
            "Múltiplos e divisores",
            "Números Inteiros",
            "Números Naturais",
            "Números Racionais",
            "Números Reais",
            "Outros",
            "Perímetro",
            "Plano cartesiano",
            "Polinômios",
            "Potenciação",
            "Probabilidade",
            "Proporcionalidade Direta e Indireta",
            "Razão",
            "Sequências e Séries",
            "Transformações geométricas",
            "Trigonometria",
            "Unidades de medida",
            "Vistas e projeções",
            "Volume"
          ],
          "Português": [
            "Elaboração do projeto de texto",
            "Adjetivos",
            "Advérbios",
            "Apreensão de sentido",
            "Classificação de texto",
            "Coesão",
            "Competência leitora",
            "Competência linguística",
            "Definição, reconhecimento e interpretação (1)",
            "Definição, reconhecimento e interpretação (2)",
            "Elementos e estrutura da narrativa",
            "Elementos notacionais da escrita",
            "Estrutura do gênero textual",
            "Figuras de linguagem",
            "Fonemas",
            "Fono-ortografia",
            "Frase, oração e período",
            "Habilidades de leitura",
            "Interjeição",
            "Locuções adjetivas",
            "Morfologia",
            "Morfossintaxe",
            "Numerais",
            "Ortografia",
            "Pontuação",
            "Pronomes",
            "Propostas de produção textual",
            "Semântica (1)",
            "Semântica (2)",
            "Sílabas",
            "Sintaxe (1)",
            "Sintaxe (2)",
            "Substantivos",
            "Tipos de texto",
            "Variação linguística",
            "Verbos"
          ]
        }
      },
      {
        "ano": "7º",
        "disciplinas": [
          "Arte",
          "Ciências",
          "Educação Física",
          "Espanhol",
          "Filosofia",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português"
        ],
        "conteúdos": {
          "Arte": [
            "Arte e Literatura",
            "Arte e tecnologia",
            "Cinema",
            "Circo",
            "Cultura artística regional",
            "Estilos Artísticos",
            "Gêneros teatrais",
            "História do teatro",
            "Idade Contemporânea",
            "Idade Média",
            "Idade Moderna",
            "Instrumentos musicais",
            "Interpretação e Análise",
            "Materiais utilizados nas artes visuais",
            "Matrizes artísticas brasileiras",
            "Obras de arte visuais",
            "Patrimônio cultural",
            "Patrimônio cultural material e imaterial"
          ],
          "Ciências": [
            "Algas",
            "Ambientes naturais",
            "Angiospermas",
            "Aplicações das Propriedades das Ondas",
            "Aplicações do Som",
            "Biologia celular",
            "Biomas",
            "Biomas brasileiros",
            "Bioquímica",
            "Biotecnologia",
            "Briófitas",
            "Cadeias e teias alimentares",
            "Calorimetria",
            "Características morfológicas e fisiológicas (1)",
            "Características morfológicas e fisiológicas (2)",
            "Ciclo celular",
            "Ciclos biogeoquímicos",
            "Classificação",
            "Climatologia",
            "Controle ambiental e saneamento básico",
            "Cosmologia Observacional",
            "Desastres Ambientais",
            "Desenvolvimento Sustentável",
            "Desequilíbrio em ecossistemas",
            "Doenças causadas por bactérias (bacterioses)",
            "Doenças causadas por protozoários (protozooses)",
            "Doenças causadas por vírus (viroses)",
            "Ecossistemas aquáticos",
            "Endemias e epidemias",
            "Estrutura Atômica",
            "Estrutura e Formação da Terra",
            "Evolução",
            "Fenômenos Sonoros",
            "Filo Annelida",
            "Filo Arthropoda",
            "Filo Chordata (Cordados)",
            "Filo Cnidaria (Cnidários)",
            "Filo Mollusca (Moluscos)",
            "Filo Nematoda (Nematódeos)",
            "Filo Porifera (Poríferos)",
            "Fisiologia celular",
            "Fluxo de energia",
            "Forças e movimento",
            "Gimnospermas",
            "Gimnospermas e angiospermas",
            "Hidrosfera",
            "Introdução à histologia",
            "Introdução ao estudo da ecologia",
            "Introdução aos Efeitos Ambientais de Substâncias Químicas",
            "IST (Infecções Sexualmente Transmissíveis)",
            "Leis de Newton",
            "Litosfera",
            "Máquinas simples",
            "Movimentos",
            "Noções de filogenética",
            "Peixes",
            "Poluentes Atmosféricos",
            "Poluição da Água",
            "Ponto de Fusão e Ponto de Ebulição",
            "Populações humanas",
            "Princípios Básicos de Propagação das Ondas",
            "Processo fotossintético",
            "Processos Industriais Químicos",
            "Propriedades de Estados da Matéria",
            "Propriedades Físicas do Som",
            "Pteridófitas",
            "Qualidades fisiológicas do som",
            "Reino Fungi",
            "Reino Metazoa (zoologia)",
            "Reino Monera",
            "Reino Plantae (biologia vegetal)",
            "Reino Protoctista",
            "Relações ecológicas",
            "Relações Interespecíficas",
            "Sais",
            "Saúde",
            "Saúde Pública",
            "Sistema imunitário e linfático",
            "Sistema locomotor",
            "Sistema nervoso e autônomo",
            "Sistema sensorial",
            "Sistema Solar",
            "Sucessão ecológica e comunidades clímax",
            "Teorias evolutivas",
            "Termodinâmica",
            "Termometria"
          ],
          "Educação Física": [
            "Alimentação, exercício físico e obesidade",
            "Conceituação de jogos, brincadeiras e esporte",
            "Conceituação de saúde e atividade física",
            "Corpo e cultura de movimento",
            "Dança e lazer",
            "Efeitos do treinamento físico",
            "Esporte e inclusão social",
            "Esportes de invasão",
            "Jogos e Simulações",
            "Modalidades coletivas",
            "Modalidades individuais"
          ],
          "Espanhol": [
            "Apreensão de sentido",
            "Léxico",
            "Pronombres",
            "Sustantivos",
            "Verbos"
          ],
          "Filosofia": [
            "Empirismo",
            "Epistemologia",
            "Estética",
            "Filosofia antiga",
            "Filosofia Contemporânea",
            "Filosofia da Ciência",
            "Filosofia medieval",
            "Filosofia Moderna",
            "Filosofia política",
            "Idealismo",
            "Liberdade",
            "Mito e religião",
            "Moral e ética",
            "O pensamento filosófico",
            "Racionalismo",
            "Valores",
            "Vida social"
          ],
          "Geografia": [
            "Biogeografia",
            "Campo",
            "Campo e cidade",
            "Climatologia (1)",
            "Climatologia (2)",
            "Comércio",
            "Comércio Internacional",
            "Desenvolvimento Econômico",
            "Desenvolvimento Sustentável",
            "Divisão territorial do mundo - Continentes",
            "Fontes de energia",
            "Geografia da religião",
            "Geografia da Saúde",
            "Geografia Urbana",
            "Geologia",
            "Geomorfologia",
            "Geopolítica e relações internacionais",
            "Geoprocessamento",
            "Gestão de Recursos Naturais",
            "Globalização e desenvolvimento técnico-científico",
            "Hidrografia",
            "História da Cartografia",
            "Industrialização",
            "Mapas Digitais e Tecnologias de Navegação",
            "Migrações",
            "Outros",
            "Pensamento espacial",
            "População e Demografia",
            "Regionalização do Brasil",
            "Sistemas de Referência Geográfica",
            "Tipos de Mapas",
            "Vegetação",
            "Visualização de Dados Espaciais"
          ],
          "História": [
            "A chegada dos imigrantes",
            "Abolição da Escravidão",
            "Absolutismo Monárquico",
            "América Colonial",
            "América Contemporânea",
            "América Espanhola no período colonial",
            "América Latina no século XX",
            "Brasil Colonial",
            "Brasil Império",
            "Colonialismo e Imperialismo",
            "Colonização europeia",
            "Culturas indígenas americanas",
            "Ditadura Civil-Militar no Brasil",
            "Ditaduras Militares na América Latina",
            "Era das Revoluções: revoluções liberais na Europa do século XIX",
            "Era Napoleônica",
            "Estudo da História",
            "Evolução do Pensamento Historiográfico",
            "Expansão dos Estados Unidos",
            "História Pública",
            "Iluminismo",
            "Independências da África",
            "Independências da América",
            "Independências da Ásia",
            "Movimento operário e o advento do socialismo",
            "Período Joanino e Independência do Brasil",
            "Populismo na América Latina",
            "Populismo no Brasil",
            "Primeira Guerra Mundial",
            "Primeira Revolução Industrial",
            "Redemocratização brasileira",
            "Renascimento",
            "República Nova",
            "Revolução Científica",
            "Revolução Inglesa",
            "Revoluções Burguesas: Independência dos Estados Unidos",
            "Revoluções Burguesas: Revolução Francesa",
            "Segunda Revolução Industrial"
          ],
          "Inglês": [
            "Adjetivos",
            "Advérbios",
            "Apreensão de sentido",
            "Artigos",
            "Conditional Sentences",
            "Conjunções",
            "Connectors",
            "Construções frasais",
            "Definição, reconhecimento e interpretação",
            "Formação de palavras",
            "Formas de perguntar",
            "Habilidades de leitura",
            "Meaning of words and expressions",
            "Prepositions",
            "Pronomes",
            "Quantifiers",
            "Semântica",
            "Substantivos",
            "Verb forms",
            "Verbo to be",
            "Verbos",
            "Verbos modais",
            "Vocabulary"
          ],
          "Matemática": [
            "Análise Combinatória",
            "Áreas de figuras planas",
            "Equações",
            "Estatística",
            "Expressões Algébricas",
            "Funções",
            "Geometria Analítica",
            "Geometria espacial",
            "Geometria Plana",
            "Localização",
            "Lógica",
            "Matemática Financeira",
            "Medidas de massa",
            "Medidas de temperatura",
            "Medidas de tempo",
            "Números Irracionais",
            "Números Naturais",
            "Números Racionais",
            "Números Reais",
            "Outros",
            "Perímetro",
            "Plano cartesiano",
            "Polinômios",
            "Potenciação",
            "Probabilidade",
            "Proporcionalidade Direta e Indireta",
            "Radiciação",
            "Razão",
            "Sequências e Séries",
            "Transformações geométricas",
            "Volume"
          ],
          "Português": [
            "Elaboração do projeto de texto",
            "Adjetivos",
            "Apreensão de sentido",
            "Argumentação",
            "Classificação de texto",
            "Coesão",
            "Competência leitora",
            "Conjunções",
            "Definição, reconhecimento e interpretação (1)",
            "Definição, reconhecimento e interpretação (2)",
            "Elementos da comunicação",
            "Elementos e estrutura da narrativa",
            "Elementos notacionais da escrita",
            "Figuras de linguagem",
            "Fono-ortografia",
            "Frase, oração e período",
            "Habilidades de leitura",
            "Morfologia",
            "Morfossintaxe",
            "Ortografia",
            "Pronomes",
            "Relações de causa e consequência",
            "Semântica",
            "Sílabas",
            "Sintaxe (1)",
            "Sintaxe (2)",
            "Substantivos",
            "Tipos de texto",
            "Variação linguística",
            "Verbos"
          ],
          "Química": [
            "Estrutura Atômica"
          ]
        }
      },
      {
        "ano": "8º",
        "disciplinas": [
          "Arte",
          "Biologia",
          "Ciências",
          "Educação Física",
          "Espanhol",
          "Filosofia",
          "Física",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português",
          "Química"
        ],
        "conteudos": {
          "Arte": [
            "Arte contemporânea",
            "Arte urbana",
            "Cinema",
            "Definições de Arte",
            "Elementos constitutivos da música",
            "Elementos constitutivos das artes visuais",
            "Estilos Artísticos",
            "Gêneros e estilos musicais",
            "Gêneros teatrais",
            "História da dança",
            "História da música",
            "História do teatro",
            "Idade Contemporânea",
            "Instrumentos musicais",
            "Interpretação e Análise",
            "Matrizes artísticas brasileiras",
            "Mercado da Arte",
            "Modernismo",
            "Movimentos Culturais e Sociais",
            "Patrimônio cultural material e imaterial",
            "Propriedades sonoras"
          ],
          "Biologia": [
            "Genética"
          ],
          "Ciências": [
            "Ácidos",
            "Ambientes naturais",
            "Aplicações do Som",
            "Biologia celular",
            "Biomas",
            "Biomas brasileiros",
            "Bioquímica",
            "Biotecnologia",
            "Briófitas",
            "Cadeias e teias alimentares",
            "Calorimetria",
            "Campos magnéticos",
            "Características morfológicas e fisiológicas",
            "Carga elétrica",
            "Ciclo celular",
            "Circuitos Elétricos",
            "Climatologia",
            "Consumo de energia elétrica",
            "Controle ambiental e saneamento básico",
            "Controle de Poluição",
            "Corrente Elétrica",
            "Cosmologia Observacional",
            "Desenvolvimento Sustentável",
            "Desequilíbrio em ecossistemas",
            "Doenças causadas por bactérias (bacterioses)",
            "Doenças causadas por protozoários (protozooses)",
            "Elementos químicos",
            "Especiação",
            "Estrutura Atômica",
            "Estrutura e função",
            "Evolução (1)",
            "Evolução (2)",
            "Fenômenos Sonoros",
            "Filo Arthropoda",
            "Filo Chordata (Cordados)",
            "Filo Cnidaria (Cnidários)",
            "Filo Platyhelmintes (Platelmintos)",
            "Fisiologia celular",
            "Fluxo de energia",
            "Forças e movimento",
            "Genética",
            "Geradores Elétricos",
            "Gimnospermas",
            "Gravitação Universal",
            "Hidrosfera",
            "Influência na Terra",
            "Introdução ao estudo da ecologia",
            "IST (Infecções Sexualmente Transmissíveis)",
            "Lei de Ohm",
            "Leis de Newton",
            "Lentes Esféricas",
            "Litosfera",
            "Manejo dos recursos naturais",
            "Máquinas simples",
            "Movimento dos corpos celestes",
            "Movimentos",
            "Óptica da visão",
            "Populações humanas",
            "Potência elétrica e Efeito Joule",
            "Processos de separação de misturas",
            "Propriedades Físicas do Som",
            "Pteridófitas",
            "Qualidades fisiológicas do som",
            "Reino Metazoa (zoologia)",
            "Reino Protoctista",
            "Relações Interespecíficas",
            "Resistência Elétrica",
            "Saúde",
            "Sistema cardiovascular",
            "Sistema genital feminino",
            "Sistema genital masculino",
            "Sistema locomotor",
            "Sistema respiratório",
            "Sistema sensorial",
            "Sistema Solar",
            "Sistema urinário",
            "Tecido muscular estriado esquelético e sistema muscular",
            "Tecnologias Ambientais",
            "Tipos de Galáxias",
            "Trabalho, energia e os teoremas"
          ],
          "Educação Física": [
            "Conceituação de jogos, brincadeiras e esporte",
            "Corpo e cultura de movimento",
            "Esporte e espetáculo",
            "Esporte e inclusão social",
            "Esportes de taco",
            "Fatores de risco à saúde",
            "Modalidades coletivas",
            "Modalidades individuais",
            "Origem e História",
            "Práticas na natureza",
            "Tipos de práticas de aventura"
          ],
          "Espanhol": [
            "Adjetivos",
            "Apreensão de sentido",
            "Fonética",
            "Léxico",
            "Numerales",
            "Pronombres",
            "Verbos"
          ],
          "Filosofia": [
            "Empirismo",
            "Epistemologia",
            "Estética",
            "Filosofia antiga",
            "Filosofia Contemporânea",
            "Filosofia da Ciência",
            "Filosofia Moderna",
            "Filosofia política",
            "Idealismo",
            "Liberdade",
            "Mito e religião",
            "Moral e ética",
            "O pensamento filosófico",
            "Racionalismo",
            "Tecnologia",
            "Vida social"
          ],
          "Física": [
            "Lançamento Vertical, Horizontal e Oblíquo"
          ],
          "Geografia": [
            "Água",
            "Campo",
            "Campo e cidade",
            "Climatologia (1)",
            "Climatologia (2)",
            "Comércio",
            "Comércio Internacional",
            "Desenvolvimento Econômico",
            "Divisão territorial do mundo - Continentes",
            "Geografia da religião",
            "Geografia da Saúde",
            "Geografia Urbana",
            "Geologia",
            "Geomorfologia",
            "Geopolítica",
            "Geopolítica e relações internacionais",
            "Gestão de Recursos Naturais",
            "Globalização e desenvolvimento técnico-científico",
            "Hidrografia",
            "História da Cartografia",
            "Industrialização",
            "Introdução à Geografia",
            "Mapas Digitais e Tecnologias de Navegação",
            "Migrações",
            "Pensamento espacial",
            "População e Demografia",
            "Princípios da Cartografia",
            "Regionalização do Brasil",
            "Sistemas de Governo",
            "Tipos de Mapas",
            "Vegetação",
            "Visualização de Dados Espaciais"
          ],
          "História": [
            "A chegada dos imigrantes",
            "Abolição da Escravidão",
            "Absolutismo Monárquico",
            "América Colonial",
            "América Contemporânea",
            "América Espanhola no período colonial",
            "América Latina no século XX",
            "Brasil Colonial",
            "Brasil Império",
            "Colonialismo e Imperialismo",
            "Colonização europeia",
            "Culturas indígenas americanas",
            "Ditadura Civil-Militar no Brasil",
            "Ditaduras Militares na América Latina",
            "Era das Revoluções: revoluções liberais na Europa do século XIX",
            "Era Napoleônica",
            "Estudo da História",
            "Evolução do Pensamento Historiográfico",
            "Expansão dos Estados Unidos",
            "História Pública",
            "Iluminismo",
            "Independências da África",
            "Independências da América",
            "Independências da Ásia",
            "Movimento operário e o advento do socialismo",
            "Período Joanino e Independência do Brasil",
            "Populismo na América Latina",
            "Populismo no Brasil",
            "Primeira Guerra Mundial",
            "Primeira Revolução Industrial",
            "Redemocratização brasileira",
            "Renascimento",
            "República Nova",
            "Revolução Científica",
            "Revolução Inglesa",
            "Revoluções Burguesas: Independência dos Estados Unidos",
            "Revoluções Burguesas: Revolução Francesa",
            "Segunda Revolução Industrial"
          ],
          "Inglês": [
            "Adjetivos",
            "Advérbios",
            "Apreensão de sentido",
            "Artigos",
            "Conditional Sentences",
            "Conjunções",
            "Connectors",
            "Construções frasais",
            "Definição, reconhecimento e interpretação",
            "Formação de palavras",
            "Formas de perguntar",
            "Habilidades de leitura",
            "Meaning of words and expressions",
            "Prepositions",
            "Pronomes",
            "Quantifiers",
            "Semântica",
            "Substantivos",
            "Verb forms",
            "Verbo to be",
            "Verbos",
            "Verbos modais",
            "Vocabulary"
          ],
          "Matemática": [
            "Análise Combinatória",
            "Áreas de figuras planas",
            "Equações",
            "Estatística",
            "Expressões Algébricas",
            "Funções",
            "Geometria Analítica",
            "Geometria espacial",
            "Geometria Plana",
            "Localização",
            "Lógica",
            "Matemática Financeira",
            "Medidas de massa",
            "Medidas de temperatura",
            "Medidas de tempo",
            "Números Irracionais",
            "Números Naturais",
            "Números Racionais",
            "Números Reais",
            "Outros",
            "Perímetro",
            "Plano cartesiano",
            "Polinômios",
            "Potenciação",
            "Probabilidade",
            "Proporcionalidade Direta e Indireta",
            "Radiciação",
            "Razão",
            "Sequências e Séries",
            "Transformações geométricas",
            "Volume"
          ],
          "Português": [
            "Elaboração do projeto de texto",
            "Adjetivos",
            "Apreensão de sentido",
            "Argumentação",
            "Classificação de texto",
            "Coesão",
            "Competência leitora",
            "Conjunções",
            "Definição, reconhecimento e interpretação (1)",
            "Definição, reconhecimento e interpretação (2)",
            "Elementos da comunicação",
            "Elementos e estrutura da narrativa",
            "Elementos notacionais da escrita",
            "Figuras de linguagem",
            "Fono-ortografia",
            "Frase, oração e período",
            "Habilidades de leitura",
            "Morfologia",
            "Morfossintaxe",
            "Ortografia",
            "Pronomes",
            "Relações de causa e consequência",
            "Semântica",
            "Sílabas",
            "Sintaxe (1)",
            "Sintaxe (2)",
            "Substantivos",
            "Tipos de texto",
            "Variação linguística",
            "Verbos"
          ],
          "Química": [
            "Estrutura Atômica"
          ]
        }
      },
      {
        "ano": "9º",
        "disciplinas": [
          "Arte",
          "Biologia",
          "Ciências",
          "Educação Física",
          "Espanhol",
          "Filosofia",
          "Física",
          "Geografia",
          "História",
          "Inglês",
          "Matemática",
          "Português",
          "Química",
          "Sociologia"
        ],
        "conteúdos": {
          "Arte": [
            "Apreciação Pessoal",
            "Arte contemporânea",
            "Arte e ciências",
            "Arte e diversidade",
            "Arte e identidade",
            "Arte e Literatura",
            "Arte e política",
            "Arte e resistência",
            "Arte e Sociedade",
            "Arte e tecnologia",
            "Arte Indiana",
            "Arte Japonesa",
            "Arte popular",
            "As cores nas artes visuais",
            "Cinema",
            "Circo",
            "Cultura artística regional",
            "Dança contemporânea",
            "Definições de Arte",
            "Elementos constitutivos da música",
            "Estilos Artísticos",
            "Gêneros e estilos musicais",
            "Grupos de instrumentistas",
            "História da dança",
            "História do teatro",
            "Idade Antiga",
            "Idade Contemporânea",
            "dade Antiga",
            "Idade Contemporânea",
            "Idade Média",
            "Idade Moderna",
            "Instrumentos musicais",
            "Interpretação e Análise",
            "Matrizes artísticas brasileiras",
            "Miscigenação artística",
            "Modernismo",
            "Movimentos Culturais e Sociais",
            "Obras de arte visuais",
            "Pré-História",
            "Profissionais do teatro",
            "Propriedades sonoras"
          ],
          "Biologia": [
            "Agnatha e superclasse dos pisces",
            "Algas",
            "Ambientes naturais",
            "Angiospermas",
            "Aspectos genéticos do funcionamento do corpo humano",
            "Audição",
            "Bioenergética",
            "Biologia celular",
            "Biomas",
            "Biomas brasileiros",
            "Bioquímica",
            "Biotecnologia",
            "Briófitas",
            "Cadeias e teias alimentares",
            "Câncer – genética do controle celular aberrante",
            "Características morfológicas e fisiológicas (1)",
            "Características morfológicas e fisiológicas (2)",
            "Ciclo celular",
            "Ciclos biogeoquímicos",
            "Citologia",
            "Citologia e microscopia",
            "Classificação",
            "Controle ambiental e saneamento básico",
            "Controle hormonal e distúrbios da digestão",
            "Darwin e Neodarwinismo",
            "Desenvolvimento embrionário",
            "Desequilíbrio em ecossistemas",
            "Dinâmica das Populações",
            "DNA – material genético e genética do funcionamento dos genes",
            "Doenças causadas por bactérias (bacterioses)",
            "Doenças causadas por protozoários (protozooses)",
            "Doenças causadas por vírus (viroses)",
            "Ecossistemas aquáticos",
            "Especiação",
            "Evolução",
            "Fermentação",
            "Filo Annelida",
            "Filo Arthropoda",
            "Filo Chordata (Cordados)",
            "Filo Poriphera (Poríferos)",
            "Fisiologia celular",
            "Gimnospermas",
            "Herança autossômica monogênica, penetrância e expressividade",
            "Introdução à histologia",
            "Introdução ao estudo da ecologia",
            "Introdução ao Reino Plantae",
            "Manejo dos recursos naturais",
            "Mutações gênicas e cromossômicas",
            "Pirâmides ecológicas",
            "Populações humanas",
            "Processo fotossintético",
            "Reino Fungi",
            "Reino Metazoa (zoologia)",
            "Reino Monera",
            "Reino Plantae",
            "Relações Interespecíficas",
            "Respiração aeróbica",
            "Saúde",
            "Seleção artificial",
            "Sistema cardiovascular",
            "Sistema digestório",
            "Sistema endócrino",
            "Sistema locomotor",
            "Sistema nervoso",
            "Sistema respiratório",
            "Sistema sensorial",
            "Sucessão ecológica e comunidades clímax",
            "Teorias evolutivas",
            "Vigilância sanitária e epidemiológica"
          ],
          "Ciências": [
            "Ácidos",
            "Algas",
            "Ambientes naturais",
            "Angiospermas",
            "Aplicações das Propriedades das Ondas (1)",
            "Aplicações das Propriedades das Ondas (2)",
            "Aplicações do Som",
            "Audição",
            "Balanceamento das equações químicas",
            "Bases",
            "Biologia celular",
            "Biomas",
            "Biomas brasileiros",
            "Biomoléculas",
            "Bioquímica",
            "Biotecnologia",
            "Briófitas",
            "Cadeias e teias alimentares",
            "Cálculos Estequiométricos Básicos",
            "Cálculos químicos",
            "Calorimetria",
            "Campos magnéticos",
            "Características morfológicas e fisiológicas",
            "Carga elétrica",
            "Ciclo celular",
            "Ciclos biogeoquímicos",
            "Circuitos Elétricos",
            "Classificação",
            "Climatologia",
            "Comportamento do Som",
            "Consumo de energia elétrica",
            "Controle ambiental e saneamento básico",
            "Controle de Poluição",
            "Corrente Elétrica",
            "Cosmologia Observacional",
            "Densidade e Massa Específica",
            "Dependência química (uso de drogas)",
            "Desastres Ambientais",
            "Desenvolvimento Sustentável",
            "Desequilíbrio em ecossistemas",
            "DNA",
            "Doenças causadas por bactérias (bacterioses)",
            "Doenças causadas por protozoários (protozooses)",
            "Doenças causadas por vírus (viroses)",
            "Ecossistemas aquáticos",
            "Elementos químicos",
            "Endemias e epidemias",
            "Energia nuclear",
            "Eritroblastose fetal",
            "Especiação",
            "Estrutura Atômica",
            "Estrutura e Formação da Terra",
            "Evolução (1)",
            "Evolução (2)",
            "Evolução humana",
            "Fenômenos Sonoros",
            "Fermentação",
            "Filo Annelida",
            "Filo Arthropoda",
            "Filo Chordata (Cordados)",
            "Filo Cnidaria (Cnidários)",
            "Filo Echinodermata (Equinodermos)",
            "Filo Mollusca (Moluscos)",
            "Filo Nematoda (Nematódeos)",
            "Filo Platyhelmintes (Platelmintos)",
            "Filo Porifera (Poríferos)",
            "Filo Poriphera (Poríferos)",
            "Fisiologia celular",
            "Fluxo de energia",
            "Forças e movimento",
            "Fundo de Micro-ondas Cósmico",
            "Genética",
            "Geologia e solo",
            "Geradores Elétricos",
            "Gimnospermas",
            "Gimnospermas e angiospermas",
            "Gravitação Universal",
            "Hidrosfera",
            "Influência na Terra",
            "Introdução ao estudo da ecologia",
            "Introdução aos Efeitos Ambientais de Substâncias Químicas",
            "IST (Infecções Sexualmente Transmissíveis)",
            "Leis de Newton",
            "Leis Ponderais",
            "Lentes Esféricas",
            "Ligações Químicas",
            "Litosfera",
            "Manejo dos recursos naturais",
            "Máquinas simples",
            "Movimento dos corpos celestes",
            "Movimentos",
            "Noções de filogenética",
            "Óptica da visão",
            "Óptica da visão: Anatomia do Olho Humano",
            "Outros",
            "Óxidos",
            "Peixes",
            "pH e pOH",
            "Poluentes Atmosféricos",
            "Poluição da Água",
            "Ponto de Fusão e Ponto de Ebulição",
            "Populações humanas",
            "Princípios Básicos de Propagação das Ondas",
            "Processo fotossintético",
            "Processos de separação de misturas",
            "Processos Industriais Químicos",
            "Propriedades de Estados da Matéria",
            "Propriedades dos Elementos",
            "Propriedades Físicas do Som",
            "Pteridófitas",
            "Qualidades fisiológicas do som",
            "Qualidades Perceptivas do Som",
            "Reflexão e Refração",
            "Reino Fungi",
            "Reino Metazoa (zoologia)",
            "Reino Monera",
            "Reino Plantae (biologia vegetal)",
            "Reino Protoctista",
            "Relações ecológicas",
            "Relações Interespecíficas",
            "Resistência Elétrica",
            "Sais",
            "Saúde",
            "Saúde Pública",
            "Separação de Misturas",
            "Sistema cardiovascular",
            "Sistema digestório",
            "Sistema endócrino",
            "Sistema genital feminino",
            "Sistema genital masculino",
            "Sistema imunitário e linfático",
            "Sistema locomotor",
            "Sistema nervoso central",
            "Sistema nervoso e autônomo",
            "Sistema nervoso periférico",
            "Sistema respiratório",
            "Sistema sensorial",
            "Sistema Solar",
            "Sistema urinário",
            "Tato",
            "Tecido adiposo",
            "Tecido hematopoiético e sanguíneo",
            "Tecido muscular",
            "Tecido muscular estriado cardíaco e tecido muscular liso",
            "Tecido nervoso",
            "Tecido ósseo, sistema esquelético e tecido cartilaginoso",
            "Tecidos (Epitelial, Muscular, Nervoso, etc.)",
            "Tecnologias Ambientais",
            "Teorias evolutivas",
            "Termodinâmica",
            "Termometria",
            "Tipos de Galáxias",
            "Tipos de Ondas",
            "Tipos de Reações Químicas",
            "Trabalho, energia e os teoremas",
            "Velocidade de Propagação da Onda"
          ],
          "Educação Física": [
            "Conceituação de expressão corporal, ginástica, danças, lutas e brigas",
            "Conceituação de jogos, brincadeiras e esporte",
            "Dança e lazer",
            "Esporte e espetáculo",
            "Esporte e inclusão social",
            "Esporte e mídia",
            "Luta",
            "Modalidades coletivas",
            "Modalidades individuais",
            "Origem e História",
            "Padrões e estereótipos de beleza corporal"
          ],
          "Espanhol": [
            "Apreensão de sentido",
            "Artículos",
            "Definição, reconhecimento e interpretação",
            "Habilidades de leitura",
            "Léxico",
            "Sustantivos",
            "Variedades linguísticas",
            "Verbos"
          ],
          "Filosofia": [
            "Epistemologia",
            "Estética",
            "Filosofia antiga",
            "Filosofia Contemporânea",
            "Filosofia da Ciência",
            "Filosofia Moderna",
            "Filosofia política",
            "Globalização",
            "Idealismo",
            "Liberdade",
            "Mito e religião",
            "Moral e ética",
            "O pensamento filosófico",
            "Racionalismo",
            "Tecnologia",
            "Valores",
            "Vida social"
          ],
          "Física": [
            "Análise de Circuitos com Geradores e Receptores",
            "Análise dimensional",
            "Aplicações das Propriedades das Ondas",
            "Aplicações do Som",
            "Aplicações dos Transformadores",
            "Calorimetria",
            "Carga elétrica",
            "Centro de massa",
            "Circuitos Elétricos",
            "Colisões entre corpos",
            "Comportamento do Som",
            "Consumo de energia elétrica",
            "Cosmologia Observacional",
            "Dilatação térmica",
            "Dissipação de energia",
            "Efeito Fotoelétrico",
            "Equações de Onda para Tubos Sonoros",
            "Equilíbrio Torque / Momento",
            "Espelhos Esféricos",
            "Espelhos Planos",
            "Fenômenos Sonoros",
            "Flutuabilidade de corpos e propriedades de fluidos",
            "Fontes de Radiação",
            "Forças e equilíbrio",
            "Forças e movimento",
            "Formação de Imagem por Lentes",
            "Geradores Elétricos",
            "Gráficos do MU e do MUV",
            "Gravitação Universal",
            "Impacto da Acústica no Bem-estar",
            "Influência na Terra",
            "Instrumentos e Técnicas Observacionais",
            "Lançamento Vertical, Horizontal e Oblíquo",
            "Leis de Newton",
            "Movimento Uniforme",
            "Movimento Uniformemente Variado",
            "Óptica da visão",
            "Outros",
            "Plano inclinado (movimento ou repouso)",
            "Potência elétrica e Efeito Joule",
            "Princípio de Stevin",
            "Princípios Básicos de Propagação das Ondas",
            "Propriedades Físicas do Som",
            "Qualidades Perceptivas do Som",
            "Reflexão e Refração",
            "Termodinâmica",
            "Termometria",
            "Tipos de Ondas",
            "Tipos de Radiação",
            "Trabalho, energia e os teoremas",
            "Tubos sonoros: Aplicações Práticas",
            "Velocidade de propagação da onda"
          ],
          "Geografia": [
            "Água",
            "Astronomia",
            "Biogeografia",
            "Campo",
            "Campo e cidade",
            "Climatologia (1)",
            "Climatologia (2)",
            "Comércio",
            "Comércio Internacional",
            "Desenvolvimento Econômico",
            "Desenvolvimento Sustentável",
            "Divisão territorial do mundo - Continentes",
            "Fontes de energia",
            "Geografia da religião",
            "Geografia da Saúde",
            "Geografia Urbana",
            "Geologia",
            "Geomorfologia",
            "Geopolítica",
            "Geopolítica e relações internacionais",
            "Geoprocessamento",
            "Gestão de Recursos Naturais",
            "Globalização e desenvolvimento técnico-científico",
            "Hidrografia",
            "História da Cartografia",
            "Industrialização",
            "Introdução à Geografia",
            "Mapas Digitais e Tecnologias de Navegação",
            "Migrações",
            "Movimentos do planeta Terra",
            "Outros",
            "Pedologia",
            "Pensamento espacial",
            "População e Demografia",
            "Princípios da Cartografia",
            "Região e Identidade Cultural",
            "Regionalização do Brasil",
            "Sistemas de Governo",
            "Sistemas de Referência Geográfica",
            "Tipos de Mapas",
            "urismo",
            "Vegetação",
            "Visualização de Dados Espaciais"
          ],
          "História": [
            "A chegada dos imigrantes",
            "A origem do ser humano",
            "A pré-história americana",
            "Abolição da Escravidão",
            "Absolutismo Monárquico",
            "América Colonial",
            "América Contemporânea",
            "América Espanhola no período colonial",
            "América Latina no século XX",
            "América Pré-Colombiana",
            "Ascensão de regimes autoritários",
            "Atualidades e panorama do Século XXI",
            "Baixa Idade Média",
            "Brasil Colonial",
            "Brasil Império",
            "Brasil Pré-Colonial",
            "Ciclos Econômicos",
            "Civilizações da Antiguidade Clássica",
            "Civilizações da Antiguidade Oriental",
            "Colonialismo e Imperialismo",
            "Colonização europeia",
            "Crises e transformações",
            "Cristianismo e Igreja Medieval",
            "Cultura e Arte Medieval",
            "Culturas indígenas americanas",
            "Ditadura Civil-Militar no Brasil",
            "Ditaduras Militares na América Latina",
            "Entreguerras",
            "Estudo da História",
            "Evolução do Pensamento Historiográfico",
            "Evolução dos Sistemas Internacionais e Instituições Globais",
            "Expansão dos Estados Unidos",
            "Expansão Islâmica e Mundo Islâmico",
            "Expansão Marítima e Comercial",
            "Feudalismo e Sociedade Feudal",
            "Formação dos Estados Nacionais",
            "Guerra Fria e suas consequências",
            "História Pública",
            "Iluminismo",
            "Império Bizantino",
            "Independências da África",
            "Independências da América",
            "Independências da Ásia",
            "Mercantilismo",
            "Movimento operário e o advento do socialismo",
            "Neoliberalismo",
            "Neolítico",
            "Outras reformas religiosas",
            "Paleolítico",
            "Período Joanino e Independência do Brasil",
            "Populismo na América Latina",
            "Populismo no Brasil",
            "Povoamento da América",
            "Povos germânicos",
            "Pré-história do Brasil: modos de vida e subsistência",
            "Primeira Guerra Mundial",
            "Primeira República",
            "Primeira Revolução Industrial",
            "Questões Contemporâneas",
            "Redemocratização brasileira",
            "Reforma Protestante",
            "Reinos e Impérios Africanos",
            "Reinos no medievo",
            "Renascimento",
            "República Nova",
            "Revolução Chinesa",
            "Revolução Inglesa",
            "Revolução Russa",
            "Revoluções Burguesas: Independência dos Estados Unidos",
            "Revoluções Burguesas: Revolução Francesa",
            "Segunda Guerra Mundial",
            "Segunda Revolução Industrial",
            "Tráfico Transatlântico de Escravizados",
            "Unificações e movimentos nacionalistas"
          ],
          "Inglês": [
            "Adjetivos",
            "Advérbios",
            "Apreensão de sentido",
            "Artículos",
            "Conditional Sentences",
            "Conjunções",
            "Connectors",
            "Construções frasais",
            "Definição, reconhecimento e interpretação",
            "Formação de palavras",
            "Formas de perguntar",
            "Habilidades de leitura",
            "Meaning of words and expressions",
            "Prepositions",
            "Pronomes",
            "Question Words",
            "Semântica",
            "Substantivos",
            "Verb forms",
            "Verbo to be",
            "Verbos",
            "Verbos modais",
            "Vocabulary"
          ],
          "Matemática": [
            "Análise Combinatória",
            "Áreas de figuras planas",
            "Áreas de superfícies tridimensionais",
            "Equações",
            "Estatística",
            "Expressões Algébricas",
            "Funções",
            "Geometria Analítica",
            "Geometria espacial",
            "Geometria Plana",
            "Inequações",
            "Localização",
            "Logaritmo",
            "Lógica (1)",
            "Lógica (2)",
            "Matemática Financeira",
            "Medidas de massa",
            "Medidas de temperatura",
            "Medidas de tempo",
            "Múltiplos e divisores",
            "Números Inteiros",
            "Números Irracionais",
            "Números Naturais",
            "Números Racionais",
            "Números Reais",
            "Perímetro",
            "Plano cartesiano",
            "Polinômios",
            "Potenciação",
            "Probabilidade",
            "Proporcionalidade Direta e Indireta",
            "Radiciação",
            "Razão",
            "Sequências e Séries",
            "Transformações geométricas",
            "Trigonometria",
            "Unidades de medida",
            "Vistas e projeções",
            "Volume"
          ],
          "Português": [
            "Elaboração do projeto de texto",
            "Adjetivos",
            "Apreensão de sentido",
            "Argumentação",
            "Classificação de texto",
            "Coesão",
            "Coesão e coerência textuais",
            "Colocação pronominal",
            "Competência leitora",
            "Competência linguística",
            "Conjunções",
            "Definição, reconhecimento e interpretação (1)",
            "Definição, reconhecimento e interpretação (2)",
            "Elementos da comunicação",
            "Elementos e estrutura da narrativa",
            "Elementos notacionais da escrita",
            "Estratégias de convencimento",
            "Estrutura do gênero textual",
            "Figuras de linguagem",
            "Fono-ortografia",
            "Frase, oração e período",
            "Habilidades de leitura",
            "Interjeição",
            "Marcadores discursivos",
            "Morfologia",
            "Morfossintaxe",
            "Numerais",
            "Ortografia",
            "Parataxe",
            "Pontuação",
            "Preposições",
            "Pronomes",
            "Relações de causa e consequência",
            "Semântica (1)",
            "Semântica (2)",
            "Sequências textuais",
            "Sílabas",
            "Sintaxe (1)",
            "Sintaxe (2)",
            "Substantivos",
            "Tipos de texto",
            "Variação linguística",
            "Verbos"
          ],
          "Química": [
            "Ácidos",
            "Aplicações da Cinética Química",
            "Aplicações da Estequiometria",
            "Bases",
            "Biomoléculas",
            "Cálculos de entalpia",
            "Cálculos de Velocidade de Reação",
            "Cálculos Estequiométricos Básicos",
            "Coloides e Suspensões",
            "Conceitos Básicos de Ácidos e Bases",
            "Controle de Poluição",
            "Corrosão",
            "Densidade e Massa Específica",
            "Desenvolvimento Sustentável",
            "Dispersões",
            "Equilíbrio iônico (1)",
            "Equilíbrio iônico (2)",
            "Estequiometria em Reações Inorgânicas",
            "Estequiometria em Soluções",
            "Estrutura Atômica (1)",
            "Estrutura Atômica (2)",
            "Fatores que afetam a velocidade de reação",
            "Fissão nuclear",
            "Funções orgânicas",
            "Hidrocarbonetos",
            "Introdução à Cinética Química",
            "Introdução aos Efeitos Ambientais de Substâncias Químicas",
            "Introdução às Propriedades Físicas",
            "Introdução às Soluções",
            "Leis Ponderais",
            "Ligações Químicas",
            "Óxidos",
            "Petróleo",
            "pH e pOH",
            "Pilhas",
            "Poluentes Atmosféricos",
            "Poluição da Água",
            "Poluição do Solo",
            "Ponto de Fusão e Ponto de Ebulição",
            "Problemas de Aplicação",
            "Processos de separação de misturas",
            "Propriedades de Estados da Matéria",
            "Propriedades dos Elementos",
            "Reações de oxi-redução",
            "Reações endo e exotérmicas",
            "Reações Orgânicas",
            "Sais",
            "Solubilidade",
            "Soluções",
            "Tipos de Reações Químicas"
          ],
          "Sociologia": [
            "Apreciação Pessoal",
            "Conceituação de expressão corporal, ginástica, danças, lutas e brigas",
            "Conceituação de jogos, brincadeiras e esporte",
            "Dança e lazer",
            "Esporte e espetáculo",
            "Esporte e inclusão social",
            "Esporte e mídia",
            "Luta",
            "Modalidades coletivas",
            "Modalidades individuais",
            "Origem e História",
            "Padrões e estereótipos de beleza corporal"
          ]
        }
      }
    ]
  }
]

export default dados;
