services:
    mysqldb:
      image: mysql:5.7
      container_name: db-csfa
      restart: unless-stopped
      env_file: ./.env
      environment:
        - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD 
        - MYSQL_DATABASE=$DB_NAME
        - MYSQL_USER=$DB_USER
        - MYSQL_PASSWORD=$DB_PASSWORD
        - MYSQL_TCP_PORT=$DB_DOCKER_PORT
      ports:
        - $DB_PORT:$DB_DOCKER_PORT
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 3
    
    app:
      depends_on:
        mysqldb:
          condition: service_healthy
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: app-csfa
      restart: unless-stopped
      env_file:
        - ./.env
      environment:
        - MYSQL_HOST=$DB_HOST
        - MYSQL_LOCAL_PORT=$DB_DOCKER_PORT
        - MYSQL_PASSWORD=$DB_PASSWORD
        - MYSQL_DATABASE=$DB_NAME
        - MYSQL_USERNAME=$DB_USER
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      stdin_open: true
      tty: true

  