import type { Metadata } from "next";
import React from "react";
import "./styles/globals.css";
import { ThemeModeScript } from "flowbite-react";
import { UserProvider } from '@auth0/nextjs-auth0/client';

// import { SessionProvider } from "next-auth/react"



export const metadata: Metadata = {
  title: "Colégio São Francisco de Asssis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, } :Readonly< { children: React.ReactNode; } >) {
  return (
    <UserProvider>
        <html lang="en" suppressHydrationWarning className="light">
          <head>
              <ThemeModeScript />
              <link rel="shortcut icon" href="/logo.webp" type="image/webp" />
          </head>
              <body className="bg-blue-900">
                  <div className="container h-auto max-w-screen-2xl flex flex-col items-center justify-center overflow-hidden">
                      {children}
                  </div>  
              </body>
        </html>
    </UserProvider>
  );
}
