import type { Metadata } from "next";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import Header from "./components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
          <ThemeModeScript />
          <link rel="shortcut icon" href="/logo.webp" type="image/webp" />
      </head>
      <body>
          <Header />
          <div className="container">
              {children}
          </div>
      </body>
    </html>
  );
}
